spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: app
    password: app
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

security:
  jwt:
    secret: CHANGE_ME_SUPER_SECRET_256BITS_MIN
    expiration: 3600000
