-- Cria o usuário APP com permissões básicas
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

BEGIN
EXECUTE IMMEDIATE 'CREATE USER APP IDENTIFIED BY app';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -01920 AND SQLCODE != -01918 THEN RAISE; END IF;
END;
/

GRANT CONNECT, RESOURCE TO APP;
GRANT UNLIMITED TABLESPACE TO APP;
