ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
EXECUTE IMMEDIATE 'CREATE USER APP IDENTIFIED BY app';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1920 AND SQLCODE != -1918 THEN
      RAISE;
END IF;
END;
/

GRANT CONNECT, RESOURCE TO APP;
GRANT UNLIMITED TABLESPACE TO APP;