CREATE TABLE roles (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  username VARCHAR2(100) UNIQUE NOT NULL,
  password VARCHAR2(255) NOT NULL,
  enabled NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE users_roles (
  user_id NUMBER NOT NULL,
  role_id NUMBER NOT NULL,
  CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE companies (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR2(150) NOT NULL,
  cnpj VARCHAR2(20)
);

CREATE TABLE emission_records (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  company_id NUMBER NOT NULL,
  record_date DATE NOT NULL,
  scope VARCHAR2(20) NOT NULL,
  amount_tco2e NUMBER(12,3) NOT NULL,
  CONSTRAINT fk_er_company FOREIGN KEY (company_id) REFERENCES companies(id)
);

CREATE TABLE reduction_schedules (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  company_id NUMBER NOT NULL,
  title VARCHAR2(150) NOT NULL,
  planned_date DATE NOT NULL,
  status VARCHAR2(30) DEFAULT 'PLANNED' NOT NULL,
  expected_reduction_tco2e NUMBER(12,3),
  CONSTRAINT fk_rs_company FOREIGN KEY (company_id) REFERENCES companies(id)
);

CREATE TABLE offset_projects (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  company_id NUMBER NOT NULL,
  type VARCHAR2(60) NOT NULL,
  description VARCHAR2(255),
  amount_tco2e NUMBER(12,3) NOT NULL,
  start_date DATE NOT NULL,
  CONSTRAINT fk_op_company FOREIGN KEY (company_id) REFERENCES companies(id)
);

INSERT INTO roles (name) VALUES ('ROLE_ADMIN');
INSERT INTO roles (name) VALUES ('ROLE_USER');

-- senha 'admin' (hash BCRYPT de exemplo)
INSERT INTO users (username, password) VALUES (
  'admin',
  '$2a$10$B1X8X8ZCz/0aVx2a7y6fYe1S3i9EwO7Wm0eXW1U6r1v0g1yR8Yy3a'
);
INSERT INTO users_roles (user_id, role_id)
SELECT u.id, r.id FROM users u, roles r
WHERE u.username='admin' AND r.name='ROLE_ADMIN';
